#ifndef GooglePlayGamesUnityPlugin_GPGSParams_h
#define GooglePlayGamesUnityPlugin_GPGSParams_h

// DO NOT EDIT THIS FILE. It is automatically generated by the Google Play Games
// Unity plugin and will be overwritten.

/*
  This section exists for the benefit of shell scripts (in particular,
  the post-processing script) that need to get information from this
  file:

AppId=928403514373
BundleId=com.Seafood.itIsRainingCatsAndDogs
ClientId=928403514373-6d3kmc2ksk3rofrvphjf467ejauhcge5.apps.googleusercontent.com

*/

#define kAppID "928403514373"
#define kBundleID "com.Seafood.itIsRainingCatsAndDogs"
#define kClientID "928403514373-6d3kmc2ksk3rofrvphjf467ejauhcge5.apps.googleusercontent.com"

#endif


