using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class CatSpawnerScript : MonoBehaviour
{
	public GameObject[] catsAndDogs;
	private Queue<GameObject> catsAndDogsQ;

	private float spawnTime = 0.3f;		// The amount of time between each spawn.
	private float spawnDelay = 0.5f;		// The amount of time before spawning starts.
	private float[] spawnPosXs = new float[] { -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6 };
	private int patternIndex = 0;
	private bool gameover;
	public static readonly string END_OF_PATTERNS = "END";

	private PlayerScript playerScript;

	void Start() {
		gameover = false;
		var count = 80;
		var createdCatsAndDogs = new GameObject[count]; 
		for (int i = 0; i < count; i++) {
			createdCatsAndDogs[i] = Instantiate(catsAndDogs[i % catsAndDogs.Length]) as GameObject;
		}
		catsAndDogsQ = new Queue<GameObject> (createdCatsAndDogs);
		playerScript = GameObject.Find("Player").GetComponent<PlayerScript>();
	}

	// to be called the first time touch started by playerScript
	public void RepeatSpawn() {
		InvokeRepeating("Spawn", spawnDelay, spawnTime);
	}

	public void QueueCatOrDog(GameObject g) {
		if (catsAndDogsQ != null && !catsAndDogsQ.Contains(g))
			catsAndDogsQ.Enqueue (g);
	}


	void  Spawn ()
	{   
		print (catsAndDogsQ.Count);
		Vector3 spawnPos = transform.position;

		if (gameover) {
			var a = Random.Range(0, spawnPosXs.Length);
			var b = Random.Range(0, spawnPosXs.Length);
			var c = Random.Range(0, spawnPosXs.Length);
			for (int i = 0; i < spawnPosXs.Length; i++) {
				if (i == a || i == b || i == c) {
					var spawnPosX = spawnPosXs[i];
					spawnPos.x = spawnPosX + Random.Range(-0.2f, 0.2f);
					var rotation = Quaternion.Euler(0.0f, 0.0f, Random.Range(0.0f, 360.0f));
					if (catsAndDogsQ.Count > 0) {
						var nextCatOrDog = catsAndDogsQ.Dequeue();
						if (nextCatOrDog != null) {
							nextCatOrDog.transform.position = spawnPos;
							nextCatOrDog.transform.rotation = rotation;
							nextCatOrDog.rigidbody2D.isKinematic = false;
						}
					}
				}
			}
		} else {

			string pattern = getPattern();
			if (pattern == END_OF_PATTERNS) {
				CancelInvoke ("Spawn");
				gameover = true;
				playerScript.OnStageCleared();
				return;
			}

			for (int i = 0; i < spawnPosXs.Length; i++) {
				if (pattern[i] == '1' || pattern[i] == 'x') {
					var spawnPosX = spawnPosXs[i];
					spawnPos.x = spawnPosX + Random.Range(-0.2f, 0.2f);
					spawnPos.y = spawnPos.y + (pattern[i] == 'x' ? Random.Range(-0.07f, 0.07f) : Random.Range(-0.6f, 0.6f));	// less variation if pavement
					var rotation = Quaternion.Euler(0.0f, 0.0f, Random.Range(0.0f, 360.0f));
					if (catsAndDogsQ.Count > 0) {
						var nextCatOrDog = catsAndDogsQ.Dequeue();
						if (nextCatOrDog != null) {
							nextCatOrDog.transform.position = spawnPos;
							nextCatOrDog.transform.rotation = rotation;
							nextCatOrDog.rigidbody2D.isKinematic = false;
						}
					}
				}
			}
		}
	}

	public void GameOver()
	{
		this.gameover = true;
	}

	public bool IsGameOver() {
		return this.gameover;
	}

	string getPattern() {
		string[] patterns = new string[] { 
			"1            ",
			"  1         1",
			" 1        1  ",
			"           1 ",
			"  1      1   ",
			"          1  ",
			"   1         ",
			"     1   1   ",
			"1 1 1     x 1",
			"1 1 1 x   x 1",
			" 1 1 x   x 1 ",
			"1 1 x   x 1 1",
			" 1 x   x 1 1 ",
			"1 x   x 1 1 1",
			" x   x 1 1 1 ",
			"1 x   x 1 1 1",
			" 1 x   x 1 1 ",
			"1 1 x   x 1 1",
			" 1 1 x   x 1 ",
			"1 1 x   x 1 1",
			" 1 x   x 1,1 ",
			"1 x   x 1 1 1",
			" x   x 1 1 1 ",
			"x   x 1 1 1 1",
			" x   x 1 1 1 ",
			"1 x   x 1 1 1",
			" 1 x   x 1 1 ",
			"1 1 x   x 1 1",
			" 1 1 x   x 1 ",
			"1 1 1 x   x 1",
			" 1 1 1 x   x ",
			"1 1 1 x   x 1",
			" 1 1 x   x 1 ",
			"1 1 x   x 1 1",
			" 1 x   x 1 1 ",
			"1 x   x 1 1 1",
			" x   x 1 1 1 ",
			"x   x 1 1 1 1",
			" x   x 1 1 1 ",
			"1 x   x 1 1 1",
			" 1 x   x 1 1 ",
			"1 1 x   x 1 1",
			" 1 1 x   x 1 ",
			"1 1 1 x   x 1",
			" 1 1 1 x   x ",
			"1 1 1 x   x 1",
			" 1 1 x   x 1 ",
			"1 1 x   x 1 1",
			" 1 x   x 1 1 ",
			"1 x   x 1 1 1",
			" x   x 1 1 1 ",
			"x   x 1 1 1 1",
			" x   x 1 1 1 ",
			"1 x   x 1 1 1",
			" 1 x   x 1 1 ",
			"1 1 x   x 1 1",
			" 1 1 x   x 1 ",
			"1 1 1 x   x 1",
			" 1 1 1 x   x ",
			"1 1 1 1 x   x",
			" 1 1 1 x   x ",
			"1 1 1 x   x 1",
			" 1 1 x   x 1 ",
			"1 1 x   x 1 1",
			" 1 x   x 1 1 ",
			"1     x 1 1 1",
			"    x x x 1 1",
			" x   x 1 1 1 ",
			"1 x   x 1 1 1",
			" 1 x   x 1 1 ",
			"1 1 x   x 1 1",
			" 1 1 x     x ",
			"1 1 1 x x   x",
			" 1 1 1 1 x   ",
			"1 1 1 1 x   x",
			" 1 1 1 x   x ",
			"1 x x x   x x",
			"         x 1 ",
			"x   x x x 1 1",
			" x   x 1 1 1 ",
			"1 x   x 1 1 1",
			" 1 x   x 1 1 ",
			"1 1 x   x 1 1",
			" 1 1 x     x ",
			"1 1 1 1 x   x",
			" 1 1 1 1 x   ",
			"1 1 1 1 x   x",
			" 1 1 1 x   x ",
			"1 x x x   x 1",
			"         x 1 ",
			"x   x x 1 1 1",
			" x   x 1 1 1 ",
			"1 x   x 1 1 1",
			" 1 x   x 1 1 ",
			"1 1 x   x 1 1",
			" 1 1 x       ",
			"1 1 1 x x   x",
			" 1 1 1 1 x   ",
			"1 1 1 1 x   x",
			" 1 1 1 x   x ",
			"1 1 1 x   x 1",
			"x        x 1 ",
			"    x x x 1 1",
			" x   x 1 1 1 ",
			"1 x   x 1 1 1",
			" 1 x   x 1 1 ",
			"1 1 x   x x 1",
			" 1 1 x     x ",
			"1 1 1 x x   x",
			" 1 1 1 1 x   ",
			"1 1 1 1 x   x",
			" 1 1 1 x   x ",
			"1 1 1 x   x 1",
			"x        x 1 ",
			"    x x 1 1 1",
			" x   x 1 1 1 ",
			"1 x   x 1 1 1",
			" 1 x   x 1 1 ",
			"1 1 x   x 1 1",
			" 1 1 x       ",
			"1 1 1 x x   x",
			" 1 1 1 1 x   ",
			"1 1 1 1 x   x",
			" 1 1 1 x   x ",
			"1 1 1 x   x 1",
			"         x 1 ",
			"   x 1 1 1 1 ",
			"             ",
			" 1 1 1 1 x   ",
			"             ",
			"   x 1 1 1 1 ",
			"             ",
			" 1 1 1 1 x   ",
			"             ",
			"   x 1 1 1 1 ",
			"             ",
			" 1 1 1 1 x   ",
			"             ",
			"   x 1 1 1 1 ",
			"             ",
			" 1 1 1 1 x   ",
			"             ",
			"   x 1 1 1 1 ",
			"             ",
			" 1 1 1 1 x   ",
			"             ",
			"   x 1 1 1 1 ",
			"             ",
			" 1 1 1 1 x   ",
			"             ",
			"   x 1 1 1 1 ",
			"             ",
			" 1 1 1 1 x   ",
			"             ",
			"   x 1 1 1 1 ",
			"             ",
			" 1 1 1 1 x   ",
			"             ",
			"   x 1 1 1 1 ",
			"             ",
			" 1 1 1 1 x   ",
			"             ",
			"   x 1 1 1 1 ",
			"             ",
			" 1 1 1 1 x   ",
			"             ",
			"   x 1 1 1 1 ",
			"             ",
			" 1 1 1 1 x   ",
			"             ",
			"   x 1 1 1 1 ",
			"             ",
			" 1 1 1 1 x   ",
			"             ",
			"1   1 1 1 1 1",
			"             ",
			"1 1 1 1 1   1",
			"             ",
			"1   1 1 1 1 1",
			"             ",
			"1 1 1 1 1   1",
			"             ",
			"1   1 1 1 1 1",
			"             ",
			"1 1 1 1 1   1",
			"             ",
			" 1   1 1 1 1 ",
			"             ",
			" 1 1 1 1   1 ",
			"             ",
			" 1   1 1 1 1 ",
			"             ",
			" 1 1 1 1   1 ",
			"             ",
			" 1   1 1 1 1 ",
			"             ",
			" 1 1 1 1   1 ",
			"             ",
			" 1   1 1 1 1 ",
			"             ",
			" 1 1 1 1   1 ",
			"             ",
			"   x 1 1 1 1 ",//start
			"             ",
			" 1 1 1 1 x   ",
			"             ",
			"1   1 1 1 1 1",
			"             ",
			"1 1 1 1 1   1",
			"             ",
			" 1   1 1 1 1 ",
			"             ",
			" 1 1 1 1   1 ",
			"             ",
			"1   1 1 1 1 1",
			"             ",
			"1 1 1 1 1   1",
			"             ",
			"   x 1 1 1 1 ",
			"             ",
			" 1 1 1 1 x   ",
			"             ",// end
			"   x 1 1 1 1 ",
			"             ",
			" 1 1 1 1 x   ",
			"             ",
			"1   1 1 1 1 1",
			"             ",
			"1 1 1 1 1   1",
			"             ",
			" 1   1 1 1 1 ",
			"             ",
			" 1 1 1 1   1 ",
			"             ",
			"1   1 1 1 1 1",
			"             ",
			"1 1 1 1 1   1",
			"             ",
			"   x 1 1 1 1 ",
			"             ",
			" 1 1 1 1 x   ",
			"             ",
			" 1 1 1 1     ",
			"1 1 1 1 1    ",
			" 1           ",
			"1   1 1 1 1 1",// start
			"   1 1 1 1 1 ",
			"    x        ",
			"   x         ",
			"             ",
			"       x     ",
			" 1 1 1 1    1",
			"1 1 1 1 1    ",
			" 1 1 1 1    1",
			"       x     ",
			"        x    ",
			"     x       ",// end
			"1    1 1 1 1 ",
			"    1 1 1 1 1",
			"1    1 1 1 1 ",
			"     x       ",
			"    x        ",
			"        x    ",
			" 1 1 1 1    1",
			"1 1 1 1 1    ",
			" 1 1 1 1    1",
			"       x     ",
			"        x    ",
			"    x        ",
			"1    1 1 1 1 ",
			"    1 1 1 1 1",
			"1    1 1 1 1 ",
			"     x      1",
			"    x        ",
			"1       x    ",
			" 1 1 1 1    1",
			"1 1 1 1 1    ",
			" 1 1 1 1    1",
			"       x     ",
			"        x    ",
			"    x       1",
			"1    1 1 1 1 ",
			"    1 1 1 1 1",
			"1    1 1 1 1 ",
			"     x      1",
			"    x        ",
			"1       x    ",
			" 1 1 1 1    1",
			"1 1 1 1 1    ",
			" 1 1 1 1    1",
			"1      x     ",
			"        x    ",
			"    x       1",
			"1    1 1 1 1 ",
			"    1 1 1 1 1",
			"1    1 1 1 1 ",
			"     x      1",
			"    x        ",
			"        x    ",
			" 1 1 1 1    1",
			"1 1 1 1 1    ",
			" 1 1 1 1    1",
			"1      x     ",
			"        x    ",
			"    x       1",
			" x   x 1 1 1 ",
			"x   x 1 1 1 1",
			" x   x 1 1 1 ",
			"1 x   x 1 1 1",
			" x   x 1 1 1 ",
			"x   x 1 1 1 1",
			" x   x 1 1 1 ",
			"1 x   x 1 1 1",
			" 1 x   x 1 1 ",
			"1 1 x   x 1 1",
			" 1 x     x 1 ",
			"1 x   x   x 1",
			" x   x x   x ",
			"x   x 1 x   x",
			"   x 1 1 x   ",
			"x   x 1 x   x",
			" x   x x   x ",
			"1 x       x 1",
			" x   x 1   x ",// Start
			"x   x 1 x   x",
			"   x 1 1 x   ",
			"x   x 1 x   x",
			" x   x x   x ",
			"1 x   x   x 1",
			"1 x   x   x 1",
			" x   x x   x ",
			"x   x 1 x   x",
			"   x 1 1 x   ",
			"x   x 1 x   1",
			" x   x x   1 ",// End
			"1 x       x 1",
			" x   1 x   x ",
			"x   x 1 x   x",
			"   x 1 1 x   ",
			"x   x 1 x   x",
			" x   x x   x ",
			"1 x   x   x 1",
			"1 x   x   x 1",
			" x   x x   x ",
			"x   x 1 x   x",
			"   x 1 1 x   ",
			"x   x 1 x   x",
			" x   x x   x ",
			"1 x       x 1",
			" x   x x   x ",
			"x   x 1 x   x",
			"   x 1 1 x   ",
			"x   x 1 x   x",
			" x   x x   x ",
			"1 x   x   x 1",
			" x   x 1   x ",
			"x   x 1 x   x",
			"   x 1 1 x   ",
			"x   x 1 x   x",
			" x   x x   x ",
			"1 x   x   x 1",
			" x   x 1   x ",
			"x   x 1 x   x",
			"   x 1 1 x   ",
			"x   x 1 x   x",
			" x   x x   x ",
			"1 x   x   x 1",
			" x   x 1   x ",
			"x   x 1 x   x",
			" x   x x   x ",
			"x   x 1 x   x",
			" x   x x   x ",
			"1 x   x   x 1",
			" x   x 1   x ",
			"x   x 1 x   x",
			" x   x x   x ",
			"x   x 1 x   x",
			" x   x x   x ",
			"1 x   x   x 1",
			" x   x 1   x ",
			"x   x 1 x   x",
			" x   x x   x ",
			"x   x 1 x   x",
			" x   x x   x ",
			"1 x   x   x 1",
			" x   x 1   x ",
			"x   x 1 x   x",
			" x   x x   x ",
			"x   x 1 x   x",
			" x   x x   x ",
			"1 x   x   x 1",
			" x   x 1   x ",
			"x   x 1 x   x",
			" x   x x   x ",
			"x   x 1 x   x",
			" x   x x   x ",
			"1     x     1",
			" x           ",
			"x   x   x   x",// Start
			"   x   x   x ",
			"1   x   x   x",
			"   x   x   x ",
			"x   x   x   x",
			"x           x",
			" x   x x   x ",
			"  x   x   x  ",
			" x   x x   x ",
			"  x   x   x  ",
			" x   x x   x ",
			"  x       x  ",
			"1 1 x   x 1 1",
			" 1 x   x 1 1 ",
			"1 1 x   x 1 1",
			" 1 x   x 1 1 ",
			"1 1 x   x 1 1",
			"  x       x  ",
			" x   x x   x ",
			" x   x x   x ",
			"  x   x   x  ",
			" x   x x   x ",
			"x           x",
			"x   x   x   x",
			"   x   x   x ",
			"x   x   x   x",
			"   x   x   x ",
			"x   x   x   x",// End
			"x   x   x   x",
			"   x   x   x ",
			"1   x   x   x",
			"   x   x   x ",
			"x   x   x   x",
			"x           x",
			" x   x x   x ",
			"  x   x   x  ",
			" x   x x   x ",
			"  x   x   x  ",
			" x   x x   x ",
			"  x   x   x  ",
			" x   x x   x ",
			"  x   x   x  ",
			" x   x x   x ",
			"  x       x  ",
			"1 1 x   x 1 1",
			" 1 x   x 1 1 ",
			"1 1 x   x 1 1",
			" 1 x   x 1 1 ",
			"1 1 x   x 1 1",
			"  x       x  ",
			" x   x x   x ",
			" x   x x   x ",
			"  x   x   x  ",
			" x   x x   x ",
			"x           x",
			"x   x   x   x",
			"   x   x   x ",
			"x   x   x   x",
			"   x   x   x ",
			"x   x   x   x",
			"x   x   x   x",
			"   x   x   x ",
			"1   x   x   x",
			"   x   x   x ",
			"x   x   x   x",
			"x           x",
			" x   x x   x ",
			"  x   x   x  ",
			" x   x x   x ",
			"  x   x   x  ",
			" x   x x   x ",
			"  x       x  ",
			"1 1 x   x 1 1",
			" 1 x   x 1 1 ",
			"1 1 x   x 1 1",
			" 1 x   x 1 1 ",
			"1 1 x   x 1 1",
			" 1 x   x 1 1 ",
			"1 1 x   x 1 1",
			" 1 x   x 1 1 ",
			"1 1 x   x 1 1",
			"  x       x  ",
			" x   x x   x ",
			" x   x x   x ",
			"  x   x   x  ",
			" x   x x   x ",
			"x           x",
			"x   x   x   x",
			"   x   x   x ",
			"x   x   x   x",
			"   x   x   x ",
			"x   x   x   x",
			"x           x",
			" x   x x   x ",
			"  x   x   x  ",
			" x   x x   x ",
			"  x   x   x  ",
			" x   x x   x ",
			"  x       x 1",
			" 1 x x   x 1 ",
			"1 1 x   x 1 1",
			" 1 1 x   x 1 ", 
			"1 1 1 x   x 1",
			" 1 1 1 x   x ",
			"  1 1 1 x   x",
			" 1 1 1 x   x ",
			"1 1 1 1 x   x",
			" 1 1 1 x   x ",
			"       x     ",
			"        x    ",
			"    x        ",// Start
			"     x       ",
			"1    1 1 1 1 ",
			"    1 1 1 1 1",
			"1    1 1 1 1 ",
			"     x       ",
			"    x        ",
			"        x    ",
			"       x     ",
			" 1 1 1 1    1",
			"1 1 1 1 1    ",
			" 1 1 1 1    1",
			"       x     ",
			"        x    ",//End
			"    x        ",
			"     x       ",
			"1    1 1 1 1 ",
			"    1 1 1 1 1",
			"1    1 1 1 1 ",
			"     x       ",
			"    x        ",
			"        x    ",
			"       x     ",
			" 1 1 1 1    1",
			"1 1 1 1 1    ",
			" 1 1 1 1    1",
			"       x     ",
			"        x    ",
			"    x        ",
			"     x       ",
			"1    1 1 1 1 ",
			"    1 1 1 1 1",
			"1    1 1 1 1 ",
			"     x       ",
			"    x        ",
			"        x    ",
			"       x     ",
			" 1 1 1 1    1",
			"1 1 1 1 1    ",
			" 1 1 1 1    1",
			"       x     ",
			"        x    ",
			"    x        ",
			"     x       ",
			"1    1 1 1 1 ",
			"    1 1 1 1 1",
			"1    1 1 1 1 ",
			"     x       ",
			"    x        ",
			"        x    ",
			"       x     ",
			" 1 1 1 1    1",
			"1 1 1 1 1    ",
			" 1 1 1 1    1",
			"       x     ",
			"        x    ",
			"    x        ",
			"     x       ",
			"1    1 1 1 1 ",
			"    1 1 1 1 1",
			"1    1 1 1 1 ",
			"     x       ",
			"    x        ",
			"        x    ",
			"       x     ",
			" 1 1 1 1    1",
			"1 1 1 1 1    ",
			" 1 1 1 1    1",
			"       x     ",
			"        x    ",
			"    x        ",
			"     x       ",
			"1    1 1 1 1 ",
			"    1 1 1 1 1",
			"1    1 1 1 1 ",
			"     x       ",
			"    x        ",
			"        x    ",
			"       x     ",
			" 1 1 1 1    1",
			"1 1 1 1 1    ",
			" 1 1 1 1    1",
			"       x     ",
			"        x    ",
			"    x        ",
			"     x       ",
			"1    1 1 1 1 ",
			"    1 1 1 1 1",
			"1    1 1 1 1 ",
			"     x       ",
			"    x        ",
			"        x    ",
			"       x     ",
			" 1 1 1 1    1",
			"1 1 1 1 1    ",
			" 1 1 1 1    1",
			"       x     ",
			"        x    ",
			"    x        ",
			"     x       ",
			"1    1 1 1 1 ",
			"    1 1 1 1 1",
			"1    1 1 1 1 ",
			"     x       ",
			"    x        ",
			"             ",
			"   x 1 1 1 1 ",//start
			"x   x        ",
			" x     x x   ",
			"1 1 x 1 1x   ",
			"        x   x",
			"   x x     x ",//end
			"   x1 1 1 1 1",
			"x   x        ",
			" x     x x   ",
			"1 1 x 1 1x   ",
			"        x   x",
			"   x x     x ",
			"   x1 1 1 1 1",
			"x   x        ",
			" x     x x   ",
			"1 1 x 1 1x   ",
			"        x   x",
			"   x x     x ",
			"   x1 1 1 1 1",
			"x   x        ",
			" x     x x   ",
			"1 1 x 1 1x   ",
			"        x   x",
			"   x x     x ",
			"   x1 1 1 1 1",
			"x   x        ",
			" x     x x   ",
			"1 1 x 1 1x   ",
			"        x   x",
			"   x x     x ",
			"   x1 1 1 1 1",
			"x   x        ",
			" x     x x   ",
			"1 1 x 1 1x   ",
			"        x   x",
			"   x x     x ",
			"   x1 1 1 1 1",
			"x   x        ",
			" x     x x   ",
			"1 1 x 1 1x   ",
			"        x   x",
			"   x x     x ",
			"             ",
			"    1 1 1 1 1",	// begin
			"1    1 1 1 1 ",
			"     1      1",
			"    x        ",
			"        x    ",
			"1      1     ",
			" 1 1 1 1    x",
			"1 1 1 1 1    ",
			" 1 1 1 1 x   ",
			"        x   x",
			"   x x     x1",
			"   x1 1 1 1 1",
			"x   x        ",
			"1x     x x   ",
			"1 1 1 1 1x   ",
			" 1 1 1 1    x",
			"1      1     ",
			"        x    ",
			"    x        ",
			"     1      1",
			"1    1 1 1 1 ",
			"    1 1 1 1 1",	// end
			"1    1 1 1 1 ",
			"    1 1 1 1 1",
			"   1 1 1 1 1 ",
			"1   1 1 1 1 1",
			" 1   1 1 1 1 ",
			"1 1   1 1 1 1",
			" 1   1 1 1 1 ",
			"111   x111111",
			"1111x   11111",
			"11111  x11111",
			"11111   11111",
			"11111x  11111",
			"11111   11111",
			"1111   xx1111",
			"111       111",
			"11xxxxxx   11",
			"x       x   x",
			"   x   x x   ",
			"x   x       x",
			" x   x 1 x x ",
			"             ",
			"   1       1 ",
			"        1    ",
			"    1        ",
			"             ",
			"        1    ",
			"   1         ",
			"             ",
			"             ",
			"             ",
			"             ",
			"             ",
			"             ",
			"             ",
			END_OF_PATTERNS
		};

		var currentPattern = patterns [patternIndex];
		patternIndex = (patternIndex + 1) % patterns.Length;
		return currentPattern;
	}
}